language: R
cache: 
    packages: true

pandoc_version: 2.5

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

addons:
  apt:
    packages:
      - libudunits2-dev
      - libxml2-dev
      - libgdal-dev